server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/learnnotice?serverTimezone=GMT&useSSL=false&useAffectedRows=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: 'wstly1221'
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
    lettuce:
      shutdown-timeout: 10000
    password: '!Wstly1221'

appId: wx22d909d630733411

secret: a3c68502ed616b22d5139166db51b428

url:
  login: https://api.weixin.qq.com/sns/jscode2session
  token: https://api.weixin.qq.com/cgi-bin/token